name: aplikasipertama
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.2
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.0.0
  image_picker: ^1.1.0
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.0
  uuid: ^4.4.0
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
