// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYtPWheQh1FYVrCi9bg1nzFSXrywC9Ye4',
    appId: '1:315093354708:web:58e62d9e13a16f12539341',
    messagingSenderId: '315093354708',
    projectId: 'umkm-app-10478',
    authDomain: 'umkm-app-10478.firebaseapp.com',
    storageBucket: 'umkm-app-10478.firebasestorage.app',
    measurementId: 'G-R18MKSVSRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgv_WaJnazQxUKjbsknR0S3TNIMywCkA',
    appId: '1:315093354708:android:e574ee7583e78262539341',
    messagingSenderId: '315093354708',
    projectId: 'umkm-app-10478',
    storageBucket: 'umkm-app-10478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA27XyEH6P3yBS2u2AmFyMOAkCz1m-k0kk',
    appId: '1:315093354708:ios:46e4509bb9450072539341',
    messagingSenderId: '315093354708',
    projectId: 'umkm-app-10478',
    storageBucket: 'umkm-app-10478.firebasestorage.app',
    iosBundleId: 'com.example.aplikasipertama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA27XyEH6P3yBS2u2AmFyMOAkCz1m-k0kk',
    appId: '1:315093354708:ios:46e4509bb9450072539341',
    messagingSenderId: '315093354708',
    projectId: 'umkm-app-10478',
    storageBucket: 'umkm-app-10478.firebasestorage.app',
    iosBundleId: 'com.example.aplikasipertama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYtPWheQh1FYVrCi9bg1nzFSXrywC9Ye4',
    appId: '1:315093354708:web:754d0687959e6f24539341',
    messagingSenderId: '315093354708',
    projectId: 'umkm-app-10478',
    authDomain: 'umkm-app-10478.firebaseapp.com',
    storageBucket: 'umkm-app-10478.firebasestorage.app',
    measurementId: 'G-349TT20MJ6',
  );
}
